name: manage-azure-policy-063e48c7
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Keys_using_elliptic_curve_cryptography_should_have_the_specified_curve_names_ff25f3c8-b739-4538-9d07-3d6d25cfb255/**'
#      - .github/workflows/manage-azure-policy-063e48c7.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_063e48c7}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Keys_using_elliptic_curve_cryptography_should_have_the_specified_curve_names_ff25f3c8-b739-4538-9d07-3d6d25cfb255/**
